Repository jupyter-server/kernel_gateway, pull requests merged in 2024-01, with the labels that each got.

#387 update workflows to point at main
  .github/workflows/tests.yml
Labels: enhancement

#384 Use jupyter server as base provider
  .github/workflows/tests.yml
  Makefile
  codecov.yml
  conftest.py
  docs/source/features.md
  kernel_gateway/auth/identity.py
  kernel_gateway/base/handlers.py
  kernel_gateway/gatewayapp.py
  kernel_gateway/jupyter_websocket/__init__.py
  kernel_gateway/jupyter_websocket/handlers.py
  kernel_gateway/mixins.py
  kernel_gateway/notebook_http/__init__.py
  kernel_gateway/notebook_http/cell/parser.py
  kernel_gateway/notebook_http/errors.py
  kernel_gateway/notebook_http/handlers.py
  kernel_gateway/notebook_http/request_utils.py
  kernel_gateway/notebook_http/swagger/builders.py
  kernel_gateway/notebook_http/swagger/handlers.py
  kernel_gateway/notebook_http/swagger/parser.py
  kernel_gateway/services/kernels/handlers.py
  kernel_gateway/services/kernels/manager.py
  kernel_gateway/services/kernels/pool.py
  kernel_gateway/services/kernelspecs/handlers.py
  kernel_gateway/services/sessions/handlers.py
  kernel_gateway/services/sessions/sessionmanager.py
  kernel_gateway/tests/__init__.py
  kernel_gateway/tests/notebook_http/cell/test_parser.py
  kernel_gateway/tests/notebook_http/swagger/test_builders.py
  kernel_gateway/tests/notebook_http/swagger/test_parser.py
  kernel_gateway/tests/notebook_http/test_request_utils.py
  kernel_gateway/tests/test_gatewayapp.py
  kernel_gateway/tests/test_jupyter_websocket.py
  kernel_gateway/tests/test_mixins.py
  kernel_gateway/tests/test_notebook_http.py
  requirements-test.txt
  requirements.txt
  setup.py
Labels: enhancement, help wanted

#389 Clean up packaging and add py312 support
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  Makefile
  codecov.yml
  docs/source/conf.py
  docs/source/http-mode.md
  kernel_gateway/_version.py
  kernel_gateway/gatewayapp.py
  pyproject.toml
  requirements-doc.txt
  requirements-test.txt
  requirements.txt
  setup.cfg
  setup.py
Labels: maintenance

#391 Apply auto-formatters
  .github/workflows/tests.yml
  CHANGELOG.md
  LICENSE.md
  README.md
  conftest.py
  docs/source/conf.py
  docs/source/config-options.md
  docs/source/devinstall.md
  docs/source/features.md
  docs/source/getting-started.md
  docs/source/http-mode.md
  docs/source/plug-in.md
  docs/source/summary-changes.md
  docs/source/uses.md
  docs/source/websocket-mode.md
  etc/api_examples/api_intro.ipynb
  etc/api_examples/endpoint_ordering.ipynb
  etc/api_examples/setting_response_metadata.ipynb
  kernel_gateway/__main__.py
  kernel_gateway/auth/identity.py
  kernel_gateway/base/handlers.py
  kernel_gateway/gatewayapp.py
  kernel_gateway/jupyter_websocket/__init__.py
  kernel_gateway/jupyter_websocket/handlers.py
  kernel_gateway/jupyter_websocket/swagger.json
  kernel_gateway/jupyter_websocket/swagger.yaml
  kernel_gateway/mixins.py
  kernel_gateway/notebook_http/__init__.py
  kernel_gateway/notebook_http/cell/parser.py
  kernel_gateway/notebook_http/errors.py
  kernel_gateway/notebook_http/handlers.py
  kernel_gateway/notebook_http/swagger/builders.py
  kernel_gateway/notebook_http/swagger/handlers.py
  kernel_gateway/notebook_http/swagger/parser.py
  kernel_gateway/services/kernels/handlers.py
  kernel_gateway/services/kernels/manager.py
  kernel_gateway/services/kernels/pool.py
  kernel_gateway/services/sessions/handlers.py
  kernel_gateway/services/sessions/sessionmanager.py
  kernel_gateway/tests/notebook_http/cell/test_parser.py
  kernel_gateway/tests/notebook_http/swagger/test_builders.py
  kernel_gateway/tests/notebook_http/swagger/test_parser.py
  kernel_gateway/tests/notebook_http/test_request_utils.py
  kernel_gateway/tests/resources/public/index.html
  kernel_gateway/tests/resources/responses.ipynb
  kernel_gateway/tests/resources/simple_api.ipynb
  kernel_gateway/tests/resources/weirdly%20named#notebook.ipynb
  kernel_gateway/tests/test_gatewayapp.py
  kernel_gateway/tests/test_jupyter_websocket.py
  kernel_gateway/tests/test_mixins.py
  kernel_gateway/tests/test_notebook_http.py
  readthedocs.yml
  setup.py
Labels: maintenance

#392 Add formatting and lint config
  .git-blame-ignore-revs
  .github/dependabot.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  CHANGELOG.md
  conftest.py
  docs/source/conf.py
  docs/source/summary-changes.md
  etc/api_examples/setting_response_metadata.ipynb
  kernel_gateway/__init__.py
  kernel_gateway/__main__.py
  kernel_gateway/auth/identity.py
  kernel_gateway/base/handlers.py
  kernel_gateway/gatewayapp.py
  kernel_gateway/jupyter_websocket/__init__.py
  kernel_gateway/jupyter_websocket/handlers.py
  kernel_gateway/mixins.py
  kernel_gateway/notebook_http/__init__.py
  kernel_gateway/notebook_http/cell/parser.py
  kernel_gateway/notebook_http/errors.py
  kernel_gateway/notebook_http/handlers.py
  kernel_gateway/notebook_http/request_utils.py
  kernel_gateway/notebook_http/swagger/builders.py
  kernel_gateway/notebook_http/swagger/handlers.py
  kernel_gateway/notebook_http/swagger/parser.py
  kernel_gateway/services/kernels/handlers.py
  kernel_gateway/services/kernels/manager.py
  kernel_gateway/services/kernels/pool.py
  kernel_gateway/services/kernelspecs/handlers.py
  kernel_gateway/services/sessions/handlers.py
  kernel_gateway/services/sessions/sessionmanager.py
  kernel_gateway/tests/notebook_http/cell/test_parser.py
  kernel_gateway/tests/notebook_http/swagger/test_builders.py
  kernel_gateway/tests/notebook_http/swagger/test_parser.py
  kernel_gateway/tests/notebook_http/test_request_utils.py
  kernel_gateway/tests/resources/kernel_api.ipynb
  kernel_gateway/tests/test_gatewayapp.py
  kernel_gateway/tests/test_jupyter_websocket.py
  kernel_gateway/tests/test_mixins.py
  kernel_gateway/tests/test_notebook_http.py
  pyproject.toml
  readthedocs.yml
Labels: maintenance

#394 Update GitHub Actions and Prep for Release
  .github/workflows/ci.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  MANIFEST.in
  RELEASE.md
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/notebook_http/__init__.py
  tests/notebook_http/cell/__init__.py
  tests/notebook_http/cell/test_parser.py
  tests/notebook_http/swagger/__init__.py
  tests/notebook_http/swagger/test_builders.py
  tests/notebook_http/swagger/test_parser.py
  tests/notebook_http/test_request_utils.py
  tests/resources/failing_code.ipynb
  tests/resources/kernel_api.ipynb
  tests/resources/public/index.html
  tests/resources/responses.ipynb
  tests/resources/simple_api.ipynb
  tests/resources/unknown_kernel.ipynb
  tests/resources/weirdly%20named#notebook.ipynb
  tests/resources/zen.ipynb
  tests/test_gatewayapp.py
  tests/test_jupyter_websocket.py
  tests/test_mixins.py
  tests/test_notebook_http.py
Labels: maintenance

#395 Add trusted publisher token permissions
  .github/workflows/publish-release.yml
Labels: maintenance
